<?xml version="1.0" encoding="utf-8"?><Database Name="QLBV" Class="QLBVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Appointments" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="AppointmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DoctorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AppointmentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Doctor_Appointment" Member="Doctor" ThisKey="DoctorID" OtherKey="DoctorID" Type="Doctor" IsForeignKey="true" />
      <Association Name="Patient_Appointment" Member="Patient" ThisKey="PatientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Departments" Member="Departments">
    <Type Name="Department">
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Department_Doctor" Member="Doctors" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Doctor" />
    </Type>
  </Table>
  <Table Name="dbo.Doctors" Member="Doctors">
    <Type Name="Doctor">
      <Column Name="DoctorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Specialty" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="WorkingSchedule" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Doctor_Appointment" Member="Appointments" ThisKey="DoctorID" OtherKey="DoctorID" Type="Appointment" />
      <Association Name="Doctor_MedicalRecord" Member="MedicalRecords" ThisKey="DoctorID" OtherKey="DoctorID" Type="MedicalRecord" />
      <Association Name="Department_Doctor" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" />
      <Association Name="User_Doctor" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Insurance" Member="Insurances">
    <Type Name="Insurance">
      <Column Name="InsuranceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InsuranceProvider" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PolicyNumber" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Insurance_Patient" Member="Patients" ThisKey="InsuranceID" OtherKey="InsuranceID" Type="Patient" />
    </Type>
  </Table>
  <Table Name="dbo.MedicalRecords" Member="MedicalRecords">
    <Type Name="MedicalRecord">
      <Column Name="RecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DoctorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Diagnosis" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Treatment" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MedicalRecord_Prescription" Member="Prescriptions" ThisKey="RecordID" OtherKey="RecordID" Type="Prescription" />
      <Association Name="Doctor_MedicalRecord" Member="Doctor" ThisKey="DoctorID" OtherKey="DoctorID" Type="Doctor" IsForeignKey="true" />
      <Association Name="Patient_MedicalRecord" Member="Patient" ThisKey="PatientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MedicalServices" Member="MedicalServices">
    <Type Name="MedicalService">
      <Column Name="ServiceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ServiceName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Notifications" Member="Notifications">
    <Type Name="Notification">
      <Column Name="NotificationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SentAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsRead" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_Notification" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payments" Member="Payments">
    <Type Name="Payment">
      <Column Name="PaymentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Method" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Patient_Payment" Member="Patient" ThisKey="PatientID" OtherKey="PatientID" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patients" Member="Patients">
    <Type Name="Patient">
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="InsuranceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Patient_Appointment" Member="Appointments" ThisKey="PatientID" OtherKey="PatientID" Type="Appointment" />
      <Association Name="Patient_MedicalRecord" Member="MedicalRecords" ThisKey="PatientID" OtherKey="PatientID" Type="MedicalRecord" />
      <Association Name="Patient_Payment" Member="Payments" ThisKey="PatientID" OtherKey="PatientID" Type="Payment" />
      <Association Name="Insurance_Patient" Member="Insurance" ThisKey="InsuranceID" OtherKey="InsuranceID" Type="Insurance" IsForeignKey="true" />
      <Association Name="User_Patient" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Prescriptions" Member="Prescriptions">
    <Type Name="Prescription">
      <Column Name="PrescriptionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecordID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Medication" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Dosage" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UsageInstructions" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="MedicalRecord_Prescription" Member="MedicalRecord" ThisKey="RecordID" OtherKey="RecordID" Type="MedicalRecord" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Role_UserRole" Member="UserRoles" ThisKey="RoleID" OtherKey="RoleID" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.StatisticsReports" Member="StatisticsReports">
    <Type Name="StatisticsReport">
      <Column Name="ReportID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GeneratedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TotalPatients" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalDoctors" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalRevenue" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.UserRoles" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="Role" ThisKey="RoleID" OtherKey="RoleID" Type="Role" IsForeignKey="true" />
      <Association Name="User_UserRole" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="User_Doctor" Member="Doctors" ThisKey="UserID" OtherKey="UserID" Type="Doctor" />
      <Association Name="User_Notification" Member="Notifications" ThisKey="UserID" OtherKey="UserID" Type="Notification" />
      <Association Name="User_Patient" Member="Patients" ThisKey="UserID" OtherKey="UserID" Type="Patient" />
      <Association Name="User_UserRole" Member="UserRoles" ThisKey="UserID" OtherKey="UserID" Type="UserRole" />
    </Type>
  </Table>
</Database>